name: Deployment pipeline

on: 
  push:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: cd backend && npm install
      - name: lint
        run: cd backend && npm run lint
  frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: cd frontend && npm install
      - name: lint
        run: cd frontend && npm run lint
  integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: frontend build
        run: cd frontend && npm install && npm run build && mv build ../backend
      - name: backend init
        run: cd backend && npm install && npm install ts-node typescript
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env: 
          CYPRESS_MONGODB_URI: ${{secrets.MONGODB_URI}}
          CYPRESS_TEST_MONGODB_URI: ${{secrets.TEST_MONGODB_URI}}
          CYPRESS_PORT: ${{secrets.PORT}}
          CYPRESS_SECRET: ${{secrets.SECRET}}
          CYPRESS_FILTER: ${{secrets.FILTER}}
          CYPRESS_AWS_BUCKET_NAME_1: ${{secrets.AWS_BUCKET_NAME_1}}
          CYPRESS_AWS_BUCKET_NAME_2: ${{secrets.AWS_BUCKET_NAME_2}}
          CYPRESS_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          CYPRESS_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        with:
          command: npm run test:e2e
          start: npm run test:server
          wait-on: 'http://localhost:3003'
