name: Deployment pipeline

on: 
  push:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: ls && cd backend && ls && npm install && ls
      - name: lint
        run: npm run lint
  frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: ls && cd frontend && ls && npm install && ls
      - name: lint
        run: npm run lint
